site :opscode

cookbook 'nginx'
cookbook 'htop'
cookbook 'ufw'
cookbook 'fail2ban'
cookbook 'unattended_upgrades', git: 'git://github.com/ChatSecure/chef-unattended-upgrades.git'
cookbook 'logwatch'
cookbook 'git'
cookbook 'user'
cookbook 'sudo'
cookbook 'database'
cookbook 'postgres'
cookbook 'python'
cookbook 'memcached'
cookbook 'openssh'
cookbook 'firewall'
cookbook 'chatsecure_users', path: 'site-cookbooks/chatsecure_users'
cookbook 'chatsecure_web', path: 'site-cookbooks/chatsecure_web'
cookbook 'chatsecure_ssl', path: 'site-cookbooks/chatsecure_ssl'
cookbook 'chatsecure_jekyll', path: 'site-cookbooks/chatsecure_jekyll'
cookbook 'chatsecure_rubdub', path: 'site-cookbooks/chatsecure_rubdub'
