site :opscode

cookbook 'nginx'
cookbook 'htop'
cookbook 'ufw'
cookbook 'fail2ban'
cookbook 'unattended_upgrades', git: 'git://github.com/ChatSecure/chef-unattended-upgrades.git'
cookbook 'logwatch'
cookbook 'git'
cookbook 'user'
cookbook 'sudo'
cookbook 'database'
cookbook 'postgres'
cookbook 'python'
cookbook 'chatsecure_users', path: 'cookbooks/chatsecure_users'
cookbook 'chatsecure_web', path: 'cookbooks/chatsecure_web'